### ISSUE TITLE
Constantly getting false-positive warning 'Selected package dshould 1.4.3 does not match dependency specification ~>1.3.2 in package mocked. Need to "dub upgrade"?'

### ISSUE THREAD

**Issue by thinkingerrol** [funkwerk/mocked#24]
Can the dependency specification be relaxed to reduce false-positive warnings?
I say false positive because Mocked 4.0.3 seems to work perfectly fine with dshould 1.4.3.

**Comment by FeepingCreature** [comment]
Yeah, that error is nonsense. Ping @belka-ew Please set it to a `>=`? If it breaks with a newer version, we need to update it anyways.

**Comment by belka-ew** [comment]
Fixed in 4.0.4.
